name: Create cloud resource
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      visibility:
        type: string
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and general context
        type: string
jobs:
  createResource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update AUTHORS
        run: |
          echo "${{ inputs.name }} and ${{ inputs.visibility }}"
      - name: Copy template file
        run: |
          cp templates/cloudResource.tf resources/${{ inputs.name }}.tf
      - name: Update new file data
        run: |
          sed -i 's/{{ bucket_name }}/${{ inputs.name }}/' resources/${{ inputs.name }}.tf \
          sed -i 's/{{ bucket_acl }}/${{ inputs.visibility }}/' resources/${{ inputs.name }}.tf \
          cat resources/${{ inputs.name }}.tf

  # createResource:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Update AUTHORS
  #       run: |
  #         git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
  #     - name: Create Pull Request
  #       uses: peter-evans/create-pull-request@v5
  #       with:
  #         commit-message: update authors
  #         title: Update AUTHORS
  #         body: Credit new contributors by updating AUTHORS
  #         branch: update-authors
